FROM python:3.7.3
WORKDIR /src
ENV HOME /home
RUN apt-get update && apt-get install -y \
	build-essential libssl-dev libffi-dev make bash zip openssl git
RUN mkdir -p /home/.local/share/virtualenvs
RUN chmod 777 /home/.local/share/virtualenvs
RUN pip install pipenv